// <auto-generated />
namespace course_proj_english_tutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserUpdated1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserUpdated1));
        
        string IMigrationMetadata.Id
        {
            get { return "202111051146372_UserUpdated#1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
